In [1]:
import numpy as np

# CREATING A ARRAY

In [12]:
mylist=[1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [13]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [14]:
z= x+y
z

array([5, 7, 9])

In [15]:
z=x-y
z

array([-3, -3, -3])

In [16]:
m=np.array([[1,8,3],[4,7,2]])

In [17]:
m

array([[1, 8, 3],
       [4, 7, 2]])

In [18]:
m.shape

(2, 3)

In [22]:
m

array([[1, 8, 3],
       [4, 7, 2]])

In [21]:
m.reshape(3,2)

array([[1, 8],
       [3, 4],
       [7, 2]])

In [30]:
a=np.arange(0,30,2)

In [31]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
a=a.reshape(3,5)

In [33]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [43]:
b=np.linspace(0,10,5)
b

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [48]:
v=np.zeros((2,5))

In [49]:
v

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
a=np.diag(z)
a

array([[-3,  0,  0],
       [ 0, -3,  0],
       [ 0,  0, -3]])

In [55]:
a=np.array([1,3,4]*2)

In [56]:
a

array([1, 3, 4, 1, 3, 4])

In [57]:
np.repeat([1,2,8],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 8, 8, 8, 8])

In [58]:
p=np.array([1,2,1])

In [61]:
np.vstack([p, 2*p])

array([[1, 2, 1],
       [2, 4, 2]])

In [62]:
p.shape

(3,)

In [68]:
x+y

array([5, 7, 9])

In [69]:
x.dot(y)

32

In [70]:
x

array([1, 2, 3])

In [71]:
y

array([4, 5, 6])

In [72]:
1+2+3+4+5+6

21

In [73]:
4+10+18

32

In [83]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(new)


[[0 1 1]
 [0 1 1]]


In [84]:
 ['a', 'b', 'c'] + [1, 2, 3]



['a', 'b', 'c', 1, 2, 3]

In [85]:
type(lambda x: x+1)

function

In [86]:
bn=np.arange(0,36)

In [107]:
r=bn.reshape(6,6)

In [108]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [114]:
r.reshape(36)[::7]


array([ 0,  7, 14, 21, 28, 35])

In [113]:
r[0:6,::-7]


array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [119]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])